import Link from "next/link"
import "./globals.css"
import { Inter } from "next/font/google"
import { getUsers } from "./api/route"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
	const data = await getUsers()

	return (
		<html lang="en">
			<body className={`${inter.className} flex flex-row`}>
				<div className="flex flex-col bg-slate-700 shadow-md shadow-zinc-600">
					{data.users.map((user) => {
						return (
							<Link
								className="text-white hover:bg-gray-50 hover:text-slate-500 rounded-md py-3 px-6"
								href={`/${user.id}`}
								key={user.id}
							>
								{user.firstName}
							</Link>
						)
					})}
				</div>
				<div>{children}</div>
			</body>
		</html>
	)
}
